### ISSUE TITLE
Не верный расчет

### ISSUE THREAD

**Issue by tim-teacher** [Brut1K/javapvtproject#1]
Homework3/src/by/it_academy/task2/Homework.java
А если у нас будет 50 новостей, 50 / 10 выходит 5, а вы потом еще +1 делаете, в итоге будет одна лишняя страница.

**Comment by Brut1K** [comment]
fixed

**Comment by tim-teacher** [comment]
javapvtproject/HomeWork/Homework3/src/by/it_academy/task2/Homework.java
Не вижу никаких исправлений, таже ошибка

**Comment by Brut1K** [comment]
fixed
Исправил сразу, просто забыл запушить.
